on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
      cache-path:
        required: true
        type: string
      valid-cache:
        required: true
        type: boolean
      os:
        required: true
        type: string
      build-deps-only:
        required: false
        type: boolean
      force-build:
        required: false
        type: boolean

jobs:
  build_deps:
    name: Build Deps
    if: ${{ !cancelled() && (inputs.build-deps-only || inputs.force-build || inputs.valid-cache != true) }}
    runs-on: ${{ inputs.os }}
    env:
      date:
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: "true"

      - name: load cached deps
        uses: actions/cache@v4
        with:
          path: ${{ inputs.cache-path }}
          key: ${{ inputs.cache-key }}

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.28.0"

      - name: setup dev on Windows
        uses: microsoft/setup-msbuild@v2

      - name: Get the date on Windows
        run: echo "date=$(Get-Date -Format 'yyyyMMdd')" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh

      - name: Build on Windows
        working-directory: ${{ github.workspace }}
        run: |
          choco install strawberryperl
          .\build_release_vs2022.bat deps
          .\build_release_vs2022.bat pack
          cd ${{ github.workspace }}/deps/build

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OrcaSlicer_dep_win64_${{ env.date }}
          path: ${{ github.workspace }}/deps/build/OrcaSlicer_dep*.zip

  build_orca:
    name: Build OrcaSlicer
    needs: [build_deps]
    if: ${{ !cancelled() && !inputs.build-deps-only && (inputs.force-build || (inputs.valid-cache == true && needs.build_deps.result == 'skipped') || (inputs.valid-cache != true && success())) }}
    uses: ./.github/workflows/build_orca.yml
    with:
      cache-key: ${{ inputs.cache-key }}
      cache-path: ${{ inputs.cache-path }}
      os: ${{ inputs.os }}
    secrets: inherit
