name: Build

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "deps/**"
      - "src/**"
      - "**/CMakeLists.txt"
      - "version.inc"
      - "localization/**"
      - "resources/**"
      - ".github/workflows/build_*.yml"

  pull_request:
    branches:
      - main
      - release/*
    paths:
      - "deps/**"
      - "src/**"
      - "**/CMakeLists.txt"
      - "version.inc"
      - ".github/workflows/build_*.yml"
      - "build_release_vs2022.bat"

  schedule:
    - cron: "0 17 * * *" # run once a day at 1 AM Singapore time (UTC+8)

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: "Only build dependencies (bypasses caching)"
        type: boolean
        default: false

jobs:
  build_all:
    name: Build Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    # Don't run scheduled builds on forks:
    if: ${{ !cancelled() && (github.event_name != 'schedule' || github.repository == 'SoftFever/OrcaSlicer') }}
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ matrix.os }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
      force-build: ${{ github.event_name == 'schedule' }}
    secrets: inherit
