name: Check Cache Windows

on:
  workflow_call:
    inputs:
      build-deps-only:
        required: false
        type: boolean
        default: false
  
jobs:
  check_cache: # determines if there is a cache and outputs variables used in caching process
    name: Check Cache Windows
    runs-on: windows-latest
    outputs:
      cache-key: ${{ steps.set_outputs.outputs.cache-key }}
      cache-path: ${{ steps.set_outputs.outputs.cache-path }}
      valid-cache: ${{ steps.cache_deps.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
        
      - name: Set outputs for Windows
        id: set_outputs
        run: |
          echo cache-key=windows-latest-cache-orcaslicer_deps-build-${{ hashFiles('deps/**') }} >> $env:GITHUB_OUTPUT
          echo cache-path=${{ github.workspace }}/deps/build/OrcaSlicer_dep >> $env:GITHUB_OUTPUT
        shell: pwsh
            
      - name: Load dependencies cache
        id: cache_deps
        uses: actions/cache@v4
        with:
          path: ${{ steps.set_outputs.outputs.cache-path }}
          key: ${{ steps.set_outputs.outputs.cache-key }}
          lookup-only: true
        
  build_deps: # call next step
    name: Build Dependencies Windows
    needs: [check_cache]
    uses: ./.github/workflows/build_deps.yml
    with:
      cache-key: ${{ needs.check_cache.outputs.cache-key }}
      cache-path: ${{ needs.check_cache.outputs.cache-path }}
      valid-cache: ${{ needs.check_cache.outputs.valid-cache == 'true' }}
      build-deps-only: ${{ inputs.build-deps-only }}
    secrets: inherit