name: Build Windows Only

on:
  push:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'localization/**'
     - 'resources/**'
     - ".github/workflows/build_*.yml"
     - 'build_release_vs2022.bat'

  pull_request:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/build_*.yml"
     - 'build_release_vs2022.bat'

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: Build Windows
    uses: ./.github/workflows/build_check_cache_windows.yml
    with:
      build-deps-only: ${{ inputs.build-deps-only || false }}
    secrets: inherit