name: Build all

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "deps/**"
      - "src/**"
      - "**/CMakeLists.txt"
      - "version.inc"
      - "localization/**"
      - "resources/**"
      - ".github/workflows/build_*.yml"

  pull_request:
    branches:
      - main
      - release/*
    paths:
      - "deps/**"
      - "src/**"
      - "**/CMakeLists.txt"
      - "version.inc"
      - ".github/workflows/build_*.yml"
      - "build_release_vs2022.bat"

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: "Only build dependencies (bypasses caching)"
        type: boolean
        default: false

jobs:
  build_all:
    name: Build All
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ matrix.os }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
    secrets: inherit
